#ifndef __WIKI_LOCAL_AUTO
#define __WIKI_LOCAL_AUTO

struct local __local_en[] = { 
	{"WELCOME", "Welcome to use Fastwiki.<br/><br/>Version: %s, %s <br/>"}, 
	{"NOT_FOUND_TITLE", "Not Found"}, 
	{"NOT_FOUND_MSG", "You can input to check again."}, 
	{"NOT_FOUND_OK", "OK"}, 
	{"EXIT_TITLE", "Exit fastwiki?"}, 
	{"EXIT_NO", "No"}, 
	{"EXIT_YES", "Yes"}, 
	{"WIKI_HREF_NOTFOUND", "Not found. But you can input to check again."}, 
	{"FIRST_PAGE", "It's the first page, press again to exit."}, 
	{"LAST_PAGE", "This is the end page"}, 
	{"MENU_FAVORITE", "Favorite"}, 
	{"ADD_FAV_MSG", "add to favorite"}, 
	{"DEL_FAV_MSG", "delete favorite"}, 
	{"CONTENT_LAST_PAGE", "It's last page"}, 
	{"HISTORY_TOTAL", "Total"}, 
	{"HISTORY_SELECT", "Select"}, 
	{"HISTORY_MANAGE", "Manage history record:"}, 
	{"HISTORY_CLEAN_MSG", "Are you sure clean all records?"}, 
	{"HISTORY_DELETE_1", "Delete "}, 
	{"HISTORY_DELETE_2", " records?"}, 
	{"HISTORY_YES", "Yes"}, 
	{"HISTORY_NO", "No"}, 
	{"FAVORITE_MANAGE", "Manage Favorite"}, 
	{"FW_SETTING", "Fastwiki Setting"}, 
	{"FW_SEL_LANG", "Select language"}, 
	{"FW_SEL_LANG_MSG", "Some label may affect after restart fastwiki"}, 
	{"FW_SEL_ENGLISH", "English"}, 
	{"FW_SEL_CHINESE", "Chinese(简体中文)"}, 
	{"FW_HOME_PAGE", "Home page"}, 
	{"FW_HP_DICT", "Dictionary"}, 
	{"CANNT_FIND_CURR_DATE", "Can't find current date in selected dictionary."}, 
	{"FW_FULL_SCREEN", "Full Screen"}, 
	{"FW_HP_BLANK", "Blank"}, 
	{"FW_HP_LAST_READ", "Last reading postion"}, 
	{"FW_HP_CURR_DATE", "current date article"}, 
	{"FW_RANDOM_ARTICLE", "Random article source"}, 
	{"FW_RANDOM_HISTORY", "History"}, 
	{"FW_RANDOM_FAVORITE", "Favorite"}, 
	{"FW_RANDOM_SELECTED_LANG", "Selected dictionary"}, 
	{"FW_RANDOM_ALL_LANG", "All dictionary"}, 
	{"FW_RANDOM_RETRY", "Please retry again"}, 
	{"FW_MUTIL_DICT_SET", "Mutil-dictionary"}, 
	{"FW_SORT_BY_TITLE", "Sort by title"}, 
	{"FW_SORT_BY_DICT", "Sort by dictionary"}, 
	{"FW_NEED_TRANS", "Translate Switch"}, 
	{"FW_TRANS_SHOW_LINES", "Translate show lines"}, 
	{"FW_DEFAULT_TRANS_DICT", "Translate dictionary"}, 
	{"FW_TRANS_ALERT_MSG", "Affect with new article, long press shows translation."}, 
	{"FW_LIBRARY_LIST", "Fastwiki dictionary list"}, 
	{"FW_LIBRARY_OK", "OK"}, 
	{"FW_LIBRARY_SELECT_ALL", "Select All"}, 
	{"FW_LIBRARY_SCAN", "Scan Sdcard"}, 
	{"FW_LIBRARY_LESS_1", "You must select at least one"}, 
	{"FW_LIBRARY_SCAN_START", "Scan sdcard may take some minitus, please wait..."}, 
	{"FW_LIBRARY_SCAN_DONE", "Scan Sdcard files done."}, 
	{"FW_ABOUT_TITLE", "About Fastwiki"}, 
	{"FW_ABOUT_MSG", "Author: Qianshanhai &lt;qianshanhai At gmail Dot com&gt; <br/>\n Version: %s, %s <br/>\nHome Page: <a href='https://fastwiki.me'>https://fastwiki.me</a> <br/>\nTwitter: <a href=http://twitter.com/fastwiki>twitter.com/fastwiki</a><br/>\nSource code: <a href=https://github.com/qianshanhai/fastwiki>github.com/qianshanhai/fastwiki</a><br/>\n"}, 
	{"FW_MENU_VIEW_OPTION", "View Option"}, 
	{"FW_MENU_LIBRARY", "Dictionary"}, 
	{"FW_MENU_HISTORY", "History"}, 
	{"FW_MENU_FAVORITE", "Favorite"}, 
	{"FW_MENU_SETTING", "Setting"}, 
	{"FW_MENU_ABOUT", "About"}, 
	{"FW_MENU_HELP", "Help"}, 
	{"FW_MENU_EXIT", "Exit"}, 
	{"FW_MENU_TOP", "Goto top"}, 
	{"FW_MENU_FORWARD", "Forward"}, 
	{"FW_MENU_ZOOM_IN", "Font ++"}, 
	{"FW_MENU_ZOOM_OUT", "Font --"}, 
	{"FW_MENU_RANDOM", "Random Article"}, 
	{"FW_MENU_DAY_MODE", "Day Mode"}, 
	{"FW_MENU_NIGHT_MODE", "Night Mode"}, 
	{"FW_MENU_ADD_TO_FAV", "Add to favorite"}, 
	{"FW_MENU_PLAY_SOUND", "Play title"}, 
	{"FW_FILE_SELECT_OK", "OK"}, 
	{"FW_FILE_SELECT_ONE", "Please select one file"}, 
	{"FW_FB_BODY_IMAGE", "Select background image"}, 
	{"FW_FB_ENABLE_BODY_IMAGE", "Enable background image"}, 
	{"FW_FB_SELECT_BODY_IMAGE", "Select background image"}, 
	{"FULL_SEARCH_MSG", "Full Search"}, 
	{"FULL_SEARCH_TEXT", "Full text Search "}, 
	{"FULL_TEXT_SHOW_TITLE", "show title only"}, 
	{"FULL_TEXT_SHOW_SOME", "show some content"}, 
	{"FULL_TEXT_SHOW_ALL", "show all content"}, 
	{"FW_AUDIO_SELECT_TITLE", "Select audio file"}, 
	{"FW_AUDIO_ENBALE_TXT", "Enable audio"}, 
	{"FW_AUDIO_SELECT_FILE", "Select one audio file"}, 
	{"FW_AUDIO_MAYBE_DAMAGE", "The audio file had damage: "}, 
	{NULL, NULL} 
};

struct local __local_zh[] = { 
	{"WELCOME", "欢迎使用 Fastwiki<br/><br/>当前版本: %s, %s <br/>"}, 
	{"NOT_FOUND_TITLE", "没有找到"}, 
	{"NOT_FOUND_MSG", "可以输入试试"}, 
	{"NOT_FOUND_OK", "确定"}, 
	{"EXIT_TITLE", "退出 fastwiki?"}, 
	{"EXIT_NO", "取消"}, 
	{"EXIT_YES", "确定"}, 
	{"WIKI_HREF_NOTFOUND", "没有找到, 不过您可以输入试一试."}, 
	{"FIRST_PAGE", "已经是第一个,再按一次退出."}, 
	{"LAST_PAGE", "已经是最后一个啦"}, 
	{"MENU_FAVORITE", "收藏夹"}, 
	{"ADD_FAV_MSG", "加入收藏"}, 
	{"DEL_FAV_MSG", "删除收藏"}, 
	{"CONTENT_LAST_PAGE", "已经是最后一页啦"}, 
	{"HISTORY_TOTAL", "总数"}, 
	{"HISTORY_SELECT", "选择"}, 
	{"HISTORY_MANAGE", "管理历史记录"}, 
	{"HISTORY_CLEAN_MSG", "清空所有记录?"}, 
	{"HISTORY_DELETE_1", "删除这 "}, 
	{"HISTORY_DELETE_2", " 条记录吗?"}, 
	{"HISTORY_YES", "确定"}, 
	{"HISTORY_NO", "取消"}, 
	{"FAVORITE_MANAGE", "管理收藏"}, 
	{"FW_SETTING", "Fastwiki 参数设置"}, 
	{"FW_SEL_LANG", "选择语言"}, 
	{"FW_SEL_LANG_MSG", "一些标签需要重启 Fastwiki 才能生效"}, 
	{"FW_SEL_ENGLISH", "英文(English)"}, 
	{"FW_SEL_CHINESE", "简体中文"}, 
	{"FW_HOME_PAGE", "首页"}, 
	{"FW_HP_DICT", "词典"}, 
	{"CANNT_FIND_CURR_DATE", "在所选的词典中没有当天日期的条目."}, 
	{"FW_FULL_SCREEN", "全屏"}, 
	{"FW_HP_BLANK", "空白页"}, 
	{"FW_HP_LAST_READ", "上一次阅读位置"}, 
	{"FW_HP_CURR_DATE", "当天的历史条目"}, 
	{"FW_RANDOM_ARTICLE", "随机条目来源"}, 
	{"FW_RANDOM_HISTORY", "历史记录"}, 
	{"FW_RANDOM_FAVORITE", "收藏夹"}, 
	{"FW_RANDOM_SELECTED_LANG", "选中的词典"}, 
	{"FW_RANDOM_ALL_LANG", "全部词典"}, 
	{"FW_RANDOM_RETRY", "请再重试一下"}, 
	{"FW_MUTIL_DICT_SET", "多字典设置"}, 
	{"FW_SORT_BY_TITLE", "按标题排序"}, 
	{"FW_SORT_BY_DICT", "按字典排序"}, 
	{"FW_NEED_TRANS", "是否需要翻译"}, 
	{"FW_TRANS_SHOW_LINES", "翻译显示的行数"}, 
	{"FW_DEFAULT_TRANS_DICT", "翻译使用的字典"}, 
	{"FW_TRANS_ALERT_MSG", "新的条目才会生效, 长按单词直接翻译"}, 
	{"FW_LIBRARY_LIST", "Fastwiki 字典列表"}, 
	{"FW_LIBRARY_OK", "确定"}, 
	{"FW_LIBRARY_SELECT_ALL", "选中全部"}, 
	{"FW_LIBRARY_SCAN", "扫描存储卡"}, 
	{"FW_LIBRARY_LESS_1", "至少选择一个词典"}, 
	{"FW_LIBRARY_SCAN_START", "扫描存储卡可能比较久, 请稍等..."}, 
	{"FW_LIBRARY_SCAN_DONE", "扫描存储卡完成"}, 
	{"FW_ABOUT_TITLE", "关于 Fastwiki"}, 
	{"FW_ABOUT_MSG", "作者: 钱善海 &lt;qianshanhai At gmail Dot com&gt; <br/>\n 版本: %s, %s <br/>\n主页: <a href='https://fastwiki.me'>https://fastwiki.me</a> <br/>\n微博: <a href=http://weibo.com/fastwiki>weibo.com/fastwiki</a><br/>\n源代码: <a href=https://github.com/qianshanhai/fastwiki>github.com/qianshanhai/fastwiki</a><br/>\n"}, 
	{"FW_MENU_VIEW_OPTION", "屏幕选项"}, 
	{"FW_MENU_LIBRARY", "词典管理"}, 
	{"FW_MENU_HISTORY", "历史记录"}, 
	{"FW_MENU_FAVORITE", "收藏夹"}, 
	{"FW_MENU_SETTING", "设置"}, 
	{"FW_MENU_ABOUT", "关于"}, 
	{"FW_MENU_HELP", "帮助"}, 
	{"FW_MENU_EXIT", "退出"}, 
	{"FW_MENU_TOP", "跳到顶部"}, 
	{"FW_MENU_FORWARD", "前一个"}, 
	{"FW_MENU_ZOOM_IN", "字体调大"}, 
	{"FW_MENU_ZOOM_OUT", "字体调小"}, 
	{"FW_MENU_RANDOM", "随机条目"}, 
	{"FW_MENU_DAY_MODE", "白天阅读模式"}, 
	{"FW_MENU_NIGHT_MODE", "夜晚阅读模式"}, 
	{"FW_MENU_ADD_TO_FAV", "收藏此条目"}, 
	{"FW_MENU_PLAY_SOUND", "播放标题"}, 
	{"FW_FILE_SELECT_OK", "确定"}, 
	{"FW_FILE_SELECT_ONE", "请先选中一个文件"}, 
	{"FW_FB_BODY_IMAGE", "选择背景图片"}, 
	{"FW_FB_ENABLE_BODY_IMAGE", "启用背景图片"}, 
	{"FW_FB_SELECT_BODY_IMAGE", "选择背景图片"}, 
	{"FULL_SEARCH_MSG", "全文搜索"}, 
	{"FULL_SEARCH_TEXT", "全文搜索设置"}, 
	{"FULL_TEXT_SHOW_TITLE", "只显示标题"}, 
	{"FULL_TEXT_SHOW_SOME", "显示部分信息"}, 
	{"FULL_TEXT_SHOW_ALL", "显示全部"}, 
	{"FW_AUDIO_SELECT_TITLE", "选择语音文件"}, 
	{"FW_AUDIO_ENBALE_TXT", "开启语音功能"}, 
	{"FW_AUDIO_SELECT_FILE", "选择语音文件"}, 
	{"FW_AUDIO_MAYBE_DAMAGE", "语音文件已经损坏: "}, 
	{NULL, NULL} 
};

#define ALL_LANG \
	{"en", __local_en}, \
	{"zh", __local_zh}, \
	{NULL, NULL}

#endif
