#ifndef __WIKI_LOCAL_AUTO
#define __WIKI_LOCAL_AUTO

struct local __local_en[] = { 
	{"SELECT_FOLDER_TITLE", "Select a folder"}, 
	{"SELECT_FOLDER_MSG", "Not found any fastwiki data file in "}, 
	{"SELECT_FOLDER_OK", "OK"}, 
	{"SELECT_FOLDER_CANCLE", "Cancle"}, 
	{"NOT_FOUND_TITLE", "Not Found"}, 
	{"NOT_FOUND_MSG", "You can input to check again."}, 
	{"NOT_FOUND_OK", "OK"}, 
	{"EXIT_TITLE", "Exit fastwiki?"}, 
	{"EXIT_NO", "No"}, 
	{"EXIT_YES", "Yes"}, 
	{"MENU_HISTORY", "history"}, 
	{"MENU_ABOUT", "About Fastwiki"}, 
	{"MENU_OPTION", "option"}, 
	{"MENU_SEL_FOLDER", "select data file folder"}, 
	{"MENU_EXIT", "exit"}, 
	{"WIKI_NOT_DATA_FILE", "Not found any data file. You can goto <br/><a href='http://fastwiki.qwrite.info'>fastwiki.qwrite.info</a> and download the convert tools to create offline data file.<br/>If you had install offline data file, then setting the folder by 'MENU->option->select data file folder'<br/><br/><br/>Chinese:<br/>没有发现数据文件, 请检查. <br/><br/>若您第一次安装, 请到<a href='http://dl.vmall.com/c0btet4irh'>官方网盘</a>下载离线数据包<br/><br/>如果已经安装了数据文件, 可以这样设置:<br/> 菜单->选项->选择数据目录"}, 
	{"WIKI_HREF_NOTFOUND", "Not found. But you can input to check again."}, 
	{"WIKI_NOT_FOUND_HOME_PAGE", "Not found home page. If you had install fastwiki data, you can check your language in:<br/>\nhttp://fastwiki.qwrite.info/en/faq.html<br/>\n if not, please tell me."}, 
	{"MENU_SET_HOME_PAGE", "Setting homepage"}, 
	{"MENU_DATE_PAGE", "Set homepage to date page"}, 
	{"MENU_RANDOM_PAGE", "Set homepage to random page"}, 
	{"FIRST_PAGE", "It's the first page, press again to exit."}, 
	{"LAST_PAGE", "This is the end page"}, 
	{"MENU_FAVORITE", "Favorite"}, 
	{"ADD_FAV_MSG", "add to favorite"}, 
	{"DEL_FAV_MSG", "delete favorite"}, 
	{"CONTENT_LAST_PAGE", "It's last page"}, 
	{"FONT_SIZE", "font size: "}, 
	{"MENU_HIDE_SHOW_MENU", "hide/show menu"}, 
	{"HISTORY_TOTAL", "Total"}, 
	{"HISTORY_SELECT", "Select"}, 
	{"HISTORY_MANAGE", "Manage history record:"}, 
	{"HISTORY_CLEAN_MSG", "Are you sure clean all records?"}, 
	{"HISTORY_DELETE_1", "Delete "}, 
	{"HISTORY_DELETE_2", " records?"}, 
	{"HISTORY_YES", "Yes"}, 
	{"HISTORY_NO", "No"}, 
	{"FAVORITE_MANAGE", "Manage Favorite"}, 
	{"SCREEN_FULL", "Full screen"}, 
	{NULL, NULL} 
};

struct local __local_zh[] = { 
	{"SELECT_FOLDER_TITLE", "选择一个目录"}, 
	{"SELECT_FOLDER_MSG", "没有发现 fastwiki 的数据文件在此目录中: "}, 
	{"SELECT_FOLDER_OK", "确定"}, 
	{"SELECT_FOLDER_CANCLE", "取消"}, 
	{"NOT_FOUND_TITLE", "没有找到"}, 
	{"NOT_FOUND_MSG", "可以输入试试"}, 
	{"NOT_FOUND_OK", "确定"}, 
	{"EXIT_TITLE", "退出 fastwiki?"}, 
	{"EXIT_NO", "取消"}, 
	{"EXIT_YES", "确定"}, 
	{"MENU_HISTORY", "历史"}, 
	{"MENU_ABOUT", "关于本软件"}, 
	{"MENU_OPTION", "选项"}, 
	{"MENU_SEL_FOLDER", "选择数据目录"}, 
	{"MENU_EXIT", "退出"}, 
	{"WIKI_NOT_DATA_FILE", "没有发现数据文件, 请检查. <br/><br/>若您第一次安装, 请到<a href='http://dl.vmall.com/c0btet4irh'>官方网盘</a>下载离线数据包<br/><br/>如果已经安装了数据文件, 可以这样设置:<br/> 菜单->选项->选择数据目录"}, 
	{"WIKI_HREF_NOTFOUND", "没有找到, 不过您可以输入试一试."}, 
	{"WIKI_NOT_FOUND_HOME_PAGE", "没有发现当前日期的信息. 如果已经安装离线数据包, 请检查数据包的语言有没有在这个列表里:<br/>\n http://fastwiki.qwrite.info/zh/faq.html<br/>\n 如果不在, 请告知作者."}, 
	{"MENU_SET_HOME_PAGE", "设置首页"}, 
	{"MENU_DATE_PAGE", "设置首页为当前日期"}, 
	{"MENU_RANDOM_PAGE", "设置首页为随机页面"}, 
	{"FIRST_PAGE", "已经是第一个,再按一次退出."}, 
	{"LAST_PAGE", "已经是最后一个啦"}, 
	{"MENU_FAVORITE", "收藏夹"}, 
	{"ADD_FAV_MSG", "加入收藏"}, 
	{"DEL_FAV_MSG", "删除收藏"}, 
	{"CONTENT_LAST_PAGE", "已经是最后一页啦"}, 
	{"FONT_SIZE", "字体大小: "}, 
	{"MENU_HIDE_SHOW_MENU", "隐藏/显示菜单"}, 
	{"HISTORY_TOTAL", "总数"}, 
	{"HISTORY_SELECT", "选择"}, 
	{"HISTORY_MANAGE", "管理历史记录"}, 
	{"HISTORY_CLEAN_MSG", "清空所有记录?"}, 
	{"HISTORY_DELETE_1", "删除这 "}, 
	{"HISTORY_DELETE_2", " 条记录吗?"}, 
	{"HISTORY_YES", "确定"}, 
	{"HISTORY_NO", "取消"}, 
	{"FAVORITE_MANAGE", "管理收藏"}, 
	{"SCREEN_FULL", "全屏"}, 
	{NULL, NULL} 
};

#define ALL_LANG \
	{"en", __local_en}, \
	{"zh", __local_zh}, \
	{NULL, NULL}

#endif
