#ifndef __WIKI_LOCAL_AUTO
#define __WIKI_LOCAL_AUTO

struct local __local_en[] = { 
	{"SELECT_FOLDER_TITLE", "Select a folder"}, 
	{"SELECT_FOLDER_MSG", "Not found any fastwiki data file in "}, 
	{"SELECT_FOLDER_OK", "OK"}, 
	{"SELECT_FOLDER_CANCLE", "Cancle"}, 
	{"NOT_FOUND_TITLE", "Not Found"}, 
	{"NOT_FOUND_MSG", "You can input to check again."}, 
	{"NOT_FOUND_OK", "OK"}, 
	{"EXIT_TITLE", "Exit fastwiki?"}, 
	{"EXIT_NO", "No"}, 
	{"EXIT_YES", "Yes"}, 
	{"MENU_HISTORY", "history"}, 
	{"MENU_ABOUT", "About Fastwiki"}, 
	{"MENU_OPTION", "option"}, 
	{"MENU_SEL_FOLDER", "select data file folder"}, 
	{"MENU_EXIT", "exit"}, 
	{"WIKI_NOT_DATA_FILE", "Not found any data file. You can goto <br/><a href='http://fastwiki.qwrite.info'>fastwiki.qwrite.info</a> and download the convert tools to create offline data file.<br/>If you had install offline data file, then setting the folder by 'MENU->option->select data file folder'<br/><br/><br/>Chinese:<br/>没有发现数据文件, 请检查. <br/><br/>若您第一次安装, 请到<a href='http://dl.vmall.com/c0btet4irh'>官方网盘</a>下载离线数据包<br/><br/>如果已经安装了数据文件, 可以这样设置:<br/> 菜单->选项->选择数据目录"}, 
	{"WIKI_HREF_NOTFOUND", "Not found. But you can input to check again."}, 
	{"WIKI_NOT_FOUND_HOME_PAGE", "Not found home page. If you had install fastwiki data, you can check your language in:<br/>\nhttp://fastwiki.qwrite.info/en/faq.html<br/>\n if not, please tell me."}, 
	{"MENU_SET_HOME_PAGE", "Setting homepage"}, 
	{"MENU_DATE_PAGE", "Set homepage to date page"}, 
	{"MENU_RANDOM_PAGE", "Set homepage to random page"}, 
	{"FIRST_PAGE", "It's the first page, press again to exit."}, 
	{"LAST_PAGE", "This is the end page"}, 
	{"MENU_FAVORITE", "Favorite"}, 
	{"ADD_FAV_MSG", "add to favorite"}, 
	{"DEL_FAV_MSG", "delete favorite"}, 
	{"CONTENT_LAST_PAGE", "It's last page"}, 
	{"FONT_SIZE", "font size: "}, 
	{"MENU_HIDE_SHOW_MENU", "hide/show menu"}, 
	{"HISTORY_TOTAL", "Total"}, 
	{"HISTORY_SELECT", "Select"}, 
	{"HISTORY_MANAGE", "Manage history record:"}, 
	{"HISTORY_CLEAN_MSG", "Are you sure clean all records?"}, 
	{"HISTORY_DELETE_1", "Delete "}, 
	{"HISTORY_DELETE_2", " records?"}, 
	{"HISTORY_YES", "Yes"}, 
	{"HISTORY_NO", "No"}, 
	{"FAVORITE_MANAGE", "Manage Favorite"}, 
	{"SCREEN_FULL", "Full screen"}, 
	{"FW_SETTING", "Fastwiki Setting"}, 
	{"FW_SEL_LANG", "Select language"}, 
	{"FW_SEL_LANG_MSG", "Some label may affect after restart fastwiki"}, 
	{"FW_SEL_ENGLISH", "English"}, 
	{"FW_SEL_CHINESE", "Chinese(简体中文)"}, 
	{"FW_HOME_PAGE", "Home page"}, 
	{"FW_FULL_SCREEN", "Full Screen"}, 
	{"FW_HP_BLANK", "Blank"}, 
	{"FW_HP_LAST_READ", "Last reading postion"}, 
	{"FW_HP_CURR_DATE", "current date article"}, 
	{"FW_MUTIL_DICT_SET", "Mutil-dictionary"}, 
	{"FW_SORT_BY_TITLE", "Sort by title"}, 
	{"FW_SORT_BY_DICT", "Sort by dictionary"}, 
	{"FW_NEED_TRANS", "Translate Switch"}, 
	{"FW_TRANS_SHOW_LINES", "Translate show lines"}, 
	{"FW_DEFAULT_TRANS_DICT", "Translate dictionary"}, 
	{"FW_LIBRARY_LIST", "Fastwiki dictionary list"}, 
	{"FW_LIBRARY_OK", "OK"}, 
	{"FW_LIBRARY_SELECT_ALL", "Select All"}, 
	{"FW_LIBRARY_SCAN", "Scan Sdcard"}, 
	{"FW_LIBRARY_LESS_1", "You must select at least one"}, 
	{"FW_LIBRARY_SCAN_DONE", "Scan Sdcard files done."}, 
	{"FW_ABOUT_TITLE", "About Fastwiki"}, 
	{"FW_ABOUT_MSG", "Author: Qianshanhai &lt;qianshanhai At gmail Dot com&gt; <br/>\n Version: %s, %s <br/>\nHome Page: <a href='http://fastwiki.me'>http://fastwiki.me</a> <br/>\nTwitter: <a href=http://twitter.com/fastwiki>twitter.com/fastwiki</a><br/>\nSource code: <a href=https://github.com/qianshanhai/fastwiki>github.com/qianshanhai/fastwiki</a><br/>\n"}, 
	{"FW_MENU_ABOUT", "About"}, 
	{"FW_MENU_HELP", "Help"}, 
	{"FW_MENU_EXIT", "Exit"}, 
	{"FW_MENU_TOP", "Goto top"}, 
	{"FW_MENU_FORWARD", "Forward"}, 
	{"FW_MENU_BACK", "Back"}, 
	{"FW_MENU_ZOOM_IN", "Font ++"}, 
	{"FW_MENU_ZOOM_OUT", "Font --"}, 
	{"FW_MENU_RANDOM", "Random Article"}, 
	{"FW_MENU_READ_MODE", "Reading Mode"}, 
	{"FW_MENU_DAY_MODE", "Day Mode"}, 
	{"FW_MENU_NIGHT_MODE", "Night Mode"}, 
	{"FW_MENU_ADD_TO_FAV", "Add to favorite"}, 
	{NULL, NULL} 
};

struct local __local_zh[] = { 
	{"SELECT_FOLDER_TITLE", "选择一个目录"}, 
	{"SELECT_FOLDER_MSG", "没有发现 fastwiki 的数据文件在此目录中: "}, 
	{"SELECT_FOLDER_OK", "确定"}, 
	{"SELECT_FOLDER_CANCLE", "取消"}, 
	{"NOT_FOUND_TITLE", "没有找到"}, 
	{"NOT_FOUND_MSG", "可以输入试试"}, 
	{"NOT_FOUND_OK", "确定"}, 
	{"EXIT_TITLE", "退出 fastwiki?"}, 
	{"EXIT_NO", "取消"}, 
	{"EXIT_YES", "确定"}, 
	{"MENU_HISTORY", "历史"}, 
	{"MENU_ABOUT", "关于本软件"}, 
	{"MENU_OPTION", "选项"}, 
	{"MENU_SEL_FOLDER", "选择数据目录"}, 
	{"MENU_EXIT", "退出"}, 
	{"WIKI_NOT_DATA_FILE", "没有发现数据文件, 请检查. <br/><br/>若您第一次安装, 请到<a href='http://dl.vmall.com/c0btet4irh'>官方网盘</a>下载离线数据包<br/><br/>如果已经安装了数据文件, 可以这样设置:<br/> 菜单->选项->选择数据目录"}, 
	{"WIKI_HREF_NOTFOUND", "没有找到, 不过您可以输入试一试."}, 
	{"WIKI_NOT_FOUND_HOME_PAGE", "没有发现当前日期的信息. 如果已经安装离线数据包, 请检查数据包的语言有没有在这个列表里:<br/>\n http://fastwiki.qwrite.info/zh/faq.html<br/>\n 如果不在, 请告知作者."}, 
	{"MENU_SET_HOME_PAGE", "设置首页"}, 
	{"MENU_DATE_PAGE", "设置首页为当前日期"}, 
	{"MENU_RANDOM_PAGE", "设置首页为随机页面"}, 
	{"FIRST_PAGE", "已经是第一个,再按一次退出."}, 
	{"LAST_PAGE", "已经是最后一个啦"}, 
	{"MENU_FAVORITE", "收藏夹"}, 
	{"ADD_FAV_MSG", "加入收藏"}, 
	{"DEL_FAV_MSG", "删除收藏"}, 
	{"CONTENT_LAST_PAGE", "已经是最后一页啦"}, 
	{"FONT_SIZE", "字体大小: "}, 
	{"MENU_HIDE_SHOW_MENU", "隐藏/显示菜单"}, 
	{"HISTORY_TOTAL", "总数"}, 
	{"HISTORY_SELECT", "选择"}, 
	{"HISTORY_MANAGE", "管理历史记录"}, 
	{"HISTORY_CLEAN_MSG", "清空所有记录?"}, 
	{"HISTORY_DELETE_1", "删除这 "}, 
	{"HISTORY_DELETE_2", " 条记录吗?"}, 
	{"HISTORY_YES", "确定"}, 
	{"HISTORY_NO", "取消"}, 
	{"FAVORITE_MANAGE", "管理收藏"}, 
	{"SCREEN_FULL", "全屏"}, 
	{"FW_SETTING", "Fastwiki 参数设置"}, 
	{"FW_SEL_LANG", "选择语言"}, 
	{"FW_SEL_LANG_MSG", "一些标签需要重启 Fastwiki 才能生效"}, 
	{"FW_SEL_ENGLISH", "英文(English)"}, 
	{"FW_SEL_CHINESE", "简体中文"}, 
	{"FW_HOME_PAGE", "首页"}, 
	{"FW_FULL_SCREEN", "全屏"}, 
	{"FW_HP_BLANK", "空白页"}, 
	{"FW_HP_LAST_READ", "上一次阅读位置"}, 
	{"FW_HP_CURR_DATE", "当天的历史条目"}, 
	{"FW_MUTIL_DICT_SET", "多字典设置"}, 
	{"FW_SORT_BY_TITLE", "按标题排序"}, 
	{"FW_SORT_BY_DICT", "按字典排序"}, 
	{"FW_NEED_TRANS", "是否需要翻译"}, 
	{"FW_TRANS_SHOW_LINES", "翻译显示的行数"}, 
	{"FW_DEFAULT_TRANS_DICT", "翻译使用的字典"}, 
	{"FW_LIBRARY_LIST", "Fastwiki 字典列表"}, 
	{"FW_LIBRARY_OK", "确定"}, 
	{"FW_LIBRARY_SELECT_ALL", "选中全部"}, 
	{"FW_LIBRARY_SCAN", "扫描存储卡"}, 
	{"FW_LIBRARY_LESS_1", "至少选择一个词典"}, 
	{"FW_LIBRARY_SCAN_DONE", "扫描存储卡完成"}, 
	{"FW_ABOUT_TITLE", "关于 Fastwiki"}, 
	{"FW_ABOUT_MSG", "作者: 钱善海 &lt;qianshanhai At gmail Dot com&gt; <br/>\n 版本: %s, %s <br/>\n主页: <a href='http://fastwiki.me'>http://fastwiki.me</a> <br/>\n微博: <a href=http://weibo.com/fastwiki>weibo.com/fastwiki</a><br/>\n源代码: <a href=https://github.com/qianshanhai/fastwiki>github.com/qianshanhai/fastwiki</a><br/>\n"}, 
	{"FW_MENU_ABOUT", "关于"}, 
	{"FW_MENU_HELP", "帮助"}, 
	{"FW_MENU_EXIT", "退出"}, 
	{"FW_MENU_TOP", "跳到顶部"}, 
	{"FW_MENU_FORWARD", "前一个"}, 
	{"FW_MENU_BACK", "后一个"}, 
	{"FW_MENU_ZOOM_IN", "字体调大"}, 
	{"FW_MENU_ZOOM_OUT", "字体调小"}, 
	{"FW_MENU_RANDOM", "随机条目"}, 
	{"FW_MENU_READ_MODE", "阅读模式"}, 
	{"FW_MENU_DAY_MODE", "白天阅读模式"}, 
	{"FW_MENU_NIGHT_MODE", "夜晚阅读模式"}, 
	{"FW_MENU_ADD_TO_FAV", "收藏此条目"}, 
	{NULL, NULL} 
};

#define ALL_LANG \
	{"en", __local_en}, \
	{"zh", __local_zh}, \
	{NULL, NULL}

#endif
